import Navigation from "./navigation";
import styles from "../styles/Home.module.css";
import Head from "next/head";
import Image from "next/image";

const About = () => (
    <div className={styles.container}>
        <Head>
            <title>{'About Moose'}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
            <Navigation />
            <main className={styles.main}>
                <h1>
                    {'About Me'}
                </h1>
                <div>
                    <Image alt={'Moose Snow'} height={350} src={"/../public/moose-snow.png"} width={300}/>
                </div>
                <div>
                    <div>{'I like playing in the snow.'}</div>
                    <div>{'I enjoy a frozen peanut butter Kong on a hot day.'}</div>
                    <div>{'I am great at fetch.'}</div>
                </div>
            </main>
        </div>
    </div>
);

export default About;