import Navigation from "./navigation";
import styles from "../styles/Home.module.css";
import Head from "next/head";
import Image from "next/image";

const Contact = () => (
    <div className={styles.container}>
        <Head>
            <title>{`Contact Moose`}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
            <Navigation />
            <main className={styles.main}>
                <h1>
                    {`Contact Me`}
                </h1>
                <div>
                    <Image alt={'Moose Barking'} height={400} src={"/../public/moose-howl.png"} width={300}/>
                </div>
                <h2>{'Howl at me!'}</h2>
                <p>{"Subscribe to Moose's mailing list"}</p>
                <form onSubmit={(event) => {
                    event.preventDefault();
                    console.log('message sent to moose')
                }}>
                    <input placeholder={"woof@dogs.com"} />
                    <button type="submit">{'Subscribe'}</button>
                </form>
            </main>
        </div>
    </div>
);

export default Contact;