import Navigation from "./navigation";
import Head from "next/head";
import Image from "next/image";

import {H1, H2, Button} from 'design-system-styled-components';
import {
    StyledContactForm,
    StyledContactFormContainer,
    StyledForm,
    StyledInput,
    StyledTextArea
} from "../styles/contact-styles";
import {StyledContainer, StyledMain} from "../styles/global-styles";

const Contact = () => (
    <StyledContainer>
        <Head>
            <title>{`Contact Moose`}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
            <Navigation />
            <StyledMain>
                <H1>
                    {`Contact Me`}
                </H1>
                <StyledContactFormContainer>
                    <div>
                        <Image alt={'Moose Barking'} height={400} src={"/../public/moose-howl.png"} width={300} />
                    </div>
                    <StyledContactForm>
                        <H2>{'Howl at me!'}</H2>
                        <StyledForm onSubmit={(event) => {
                            event.preventDefault();
                            console.log('message sent to moose')
                        }}
                        >
                            <StyledTextArea
                                placeholder={'Type a message to Moose'}
                            />
                            <StyledInput
                                id={'submitter-name'}
                                label={'Your Name'}
                            />
                            <Button type="submit">{'Send to Moose'}</Button>
                        </StyledForm>
                    </StyledContactForm>
                </StyledContactFormContainer>
            </StyledMain>
        </div>
    </StyledContainer>
);

export default Contact;