import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navigation from "./navigation";
import Image from "next/image";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>{`Moose's Website`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navigation />
        <main className={styles.main}>
          <h1>
            {`Hi, I'm Moose`}
          </h1>
          <div>
            <Image alt={'Moose Headshot'} height={400} src={"/../public/moose.png"} width={300}/>
          </div>
          <p>{`Welcome to Moose's corner of the web.`}</p>
        </main>
      </div>
    </div>
  )
}
